Build images in travis, update docs and Makefile
ONSdigital/ssdc-rm-dockerfiles pull request #14
Opened 2022-07-29 07:08 UTC by AdamHawtin

# Motivation and Context

We should test the image builds in Travis, and keep the docs and Makefile up to date.

# What has changed

- Add travis yaml running all the image builds
- Update Makefile
- Update README

# How to test?

Check the Travis build. It should fail until #13 is merged.

# Links

https://trello.com/c/Ip5SuYx5/283-test-tooling-image-builds-in-travis

2022-07-29 07:24 UTC, KieranWardle approved these changes

2022-07-29 13:44 UTC, hbrace approved these changes

2022-08-05 12:24 UTC, davidmort requested changes
a bit pernickity but can we update the PR title/description now that we're doing github action stuff instead of travis, other looks great 👍

2022-08-05 13:00 UTC, davidmort approved these changes

2022-08-05 13:07 UTC, merged