271 Add cloud sql auth proxy
ONSdigital/ssdc-rm-dockerfiles pull request #15
Opened 2022-08-04 10:33 UTC by AdamHawtin

# WIP

# Motivation and Context

We need a cloudsql proxy image

# What has changed

- Add cloudsql proxy dockerfile
- Update Makefile and README
- Update paths to be more consistent with naming

# How to test?

Try building the image and using it, WIP.

# Links

https://trello.com/c/nI77Ukwq/271-add-cloud-sql-auth-proxy-to-bastion-vm-5

2022-08-15 07:07 UTC, davidmort requested changes

2022-08-15 07:07 UTC, davidmort commented on cloudsql-proxy/Dockerfile
> +RUN apk update && apk add --no-cache postgresql-client
whats the reason for installing this?

2022-08-16 07:52 UTC, davidmort approved these changes

2022-08-16 08:02 UTC, apolloakora commented
We should document the github workflow where it logs into dockerhub but that is not in the scope of this - just noticed that.

2022-08-16 08:26 UTC, apolloakora requested changes

2022-08-16 08:26 UTC, apolloakora commented on cloudsql-proxy/Dockerfile
> +FROM eu.gcr.io/cloudsql-docker/gce-proxy:1.31.2-alpine
When I ran docker scan on the cloudsql-proxy image it produced a critical severity in zlib (Out of bounds write) which it said was fixed in zlib 1.2.12-r2

2022-08-16 08:38 UTC, apolloakora requested changes

2022-08-16 08:38 UTC, apolloakora commented on cloudsql-proxy/Dockerfile
> +CMD ./cloud_sql_proxy -enable_iam_login -instances=$CLOUDSQL_INSTANCE_ADDRESS -ip_address_types=PRIVATE
```suggestion
CMD ./cloud_sql_proxy -enable_iam_login -instances=$CLOUDSQL_INSTANCE_ADDRESS -ip_address_types=PRIVATE

```

2022-08-16 09:26 UTC, ryangrundy7 commented on cloudsql-proxy/Dockerfile
> +FROM eu.gcr.io/cloudsql-docker/gce-proxy:1.31.2-alpine
I don't think there's much we can do about this. It's the latest version of the dockerfile so there's no current fix for it

2022-08-16 11:03 UTC, apolloakora approved these changes

2022-08-16 11:57 UTC, davidmort commented on cloudsql-proxy/Dockerfile
> +FROM eu.gcr.io/cloudsql-docker/gce-proxy:1.31.2-alpine
reading up on that zlib cve it doesn't look like we'd be affected by it anyway 👍

2022-08-17 08:23 UTC, merged