224 build a python pipenv base image
ONSdigital/ssdc-rm-dockerfiles pull request #16
Opened 2022-08-26 09:34 UTC by KieranWardle

# Motivation and Context
We currently use the standard python base image and install pipenv every time we build a service image

# What has changed
Created base python build image containing pipenv and other dependencies required for building our python services

2022-08-30 08:24 UTC, AdamHawtin requested changes
The README and Makefile need updating.

2022-09-07 08:30 UTC, AdamHawtin commented on Makefile
> +python-pipenv:
`python-pipenv` need to be added to the `.PHONY` list at the top, otherwise `Make` doesn't run the command properly because it coincides with a directory name.

2022-09-07 08:42 UTC, AdamHawtin commented on Makefile
> +	docker build ./python-pipenv -t europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/python-pipenv:latest
We might want to make this build the `ons-ci-rm` image, otherwise we would always have to re-tag it if we are trying to have our other local builds use a locally built version of this image. That or include the instructions/command in the README for re-tagging the image to make it clear how/when to do this.

2022-09-07 09:38 UTC, AdamHawtin commented on Makefile
> +	docker build ./python-pipenv -t europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/python-pipenv:latest
Since this is building with the `ssdc-rm-ci` registry name, it won't locally be used in local builds of other services using the `ons-ci-rm` name unless we re-tag it. Perhaps this should build with the `ons-ci-rm` name since that's the image we'll use in most cases, or the README should include a note about this and the re-tagging command to make it clearer how to make use of a locally built `python-pipenv` image.

2022-09-09 08:05 UTC, AdamHawtin commented on python-pipenv/Dockerfile
> +FROM python:3.10.6-alpine@sha256:5b4e425e03038da758a35dc6f4473b4cf9bbadb9a7cdc2766d5d1d10ef1c9ca9
I think we're better off reverting this to the default `slim` too to avoid potential compatibility issues.

2022-09-09 10:14 UTC, AdamHawtin approved these changes
👍 Working nicely with all the builds for me locally.

2022-09-12 07:56 UTC, LukeLoze1 approved these changes

2022-09-12 12:26 UTC, merged