Added venom dockerfile
ONSdigital/ssdc-rm-dockerfiles pull request #30
Opened 2023-11-10 07:12 UTC by KieranWardle

# Motivation and Context
we're adding venom OWASP tests to our pipeline

# What has changed
Added docker file for venom tests

# How to test?
Build and deploy to dev env to run tests against your RH-UI

2023-11-14 09:26 UTC, ryangrundy7 requested changes
Would be nice to have a command in the makefile to build this

2023-11-14 11:03 UTC, ryangrundy7 commented on owasp-venom/venom_tests.yml
> +  target_site: "http://srm-rh-ui:80/en/start"
So this url is for the new rh-ui which isn't being used yet. Might be worth changing this to the current one

2023-11-14 16:01 UTC, ryangrundy7 commented on owasp-venom/venom_tests.yml
I think this test suite is out of date. Might be worth taking a look at the one on the owasp secure headers github repo https://github.com/oshp/oshp-validator/blob/main/tests_suite.yml

2023-11-21 09:31 UTC, ryangrundy7 commented on Makefile
> +	docker build ./owasp-venom -t europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-owasp-venom:latest
The image in the kubernetes yml is called `europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/venom:latest`. Actually it doesn't include the ssdc-rm-ci repo but we're only gonna use it for preprod so we can use this command for dev environments

2023-11-21 09:31 UTC, ryangrundy7 commented on Makefile
> +	docker build ./owasp-venom -t europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-owasp-venom:latest
The image in the kubernetes yml is called `europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/venom:latest`. Actually it doesn't include the ssdc-rm-ci repo but we're only gonna use it for preprod so we can use this command for dev environments

2023-11-23 09:18 UTC, ryangrundy7 approved these changes

2023-11-23 11:04 UTC, dbanks91 approved these changes

2023-11-24 10:11 UTC, merged